/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GameLayoutImport } from './routes/_game-layout'
import { Route as GameLayoutGameGameIdImport } from './routes/_game-layout/game/$gameId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const GameLayoutRoute = GameLayoutImport.update({
  id: '/_game-layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const GameLayoutGameGameIdRoute = GameLayoutGameGameIdImport.update({
  path: '/game/$gameId',
  getParentRoute: () => GameLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_game-layout': {
      id: '/_game-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GameLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_game-layout/game/$gameId': {
      id: '/_game-layout/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameLayoutGameGameIdImport
      parentRoute: typeof GameLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  GameLayoutRoute: GameLayoutRoute.addChildren({ GameLayoutGameGameIdRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_game-layout"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_game-layout": {
      "filePath": "_game-layout.tsx",
      "children": [
        "/_game-layout/game/$gameId"
      ]
    },
    "/_game-layout/game/$gameId": {
      "filePath": "_game-layout/game/$gameId.tsx",
      "parent": "/_game-layout"
    }
  }
}
ROUTE_MANIFEST_END */
